CREATE TABLE DEPARTMENT(
DNAME VARCHAR2(20),
DNUMBER NUMBER PRIMARY KEY,
MGRSSN VARCHAR2(20),
MGRSTARTDATE DATE
);



CREATE TABLE EMPLOYEE(
FNAME VARCHAR2(20),
MINIT CHAR(1),
LNAME VARCHAR2(20),
SSN VARCHAR2(15) PRIMARY KEY,
BDATE DATE,
ADDRESS VARCHAR2(100),
SEX CHAR(1),
SALARY NUMBER,
SUPERSSN VARCHAR2(15),
DNO NUMBER,
CONSTRAINT FK_DEPT
FOREIGN KEY (DNO)
REFERENCES DEPARTMENT(DNUMBER)
);

INSERT INTO DEPARTMENT
(DNAME,DNUMBER,MGRSSN,MGRSTARTDATE)
VALUES ('HR',1,NULL,
DATE '2022-01-01'),
('Research',2,NULL,
DATE '2022-10-01'),
('Finance',3,NULL,
DATE '2020-01-01');

SELECT E.FNAME,
E.LNAME,
E.SALARY * 1.1 AS INCREASED_SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DNO = D.DNUMBER
WHERE D.DNAME='Research';

SELECT
SUM(E.SALARY) AS TOTAL,
MAX(E.SALARY) AS MAX,
MIN(E.SALARY) AS MIN,
AVG(E.SALARY) AS AVERAGE
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DNO = D.DNUMBER
WHERE D.DNAME='Finance';

SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE DNO = 5;

SELECT D.DNAME,
COUNT(*) AS EMP_COUNT
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DNO = D.DNUMBER
GROUP BY D.DNUMBER, D.DNAME
HAVING COUNT(*) >= 2;

SELECT FNAME,LNAME,BDATE
FROM EMPLOYEE
WHERE BDATE BETWEEN
DATE '1990-01-01'
AND DATE '1999-12-31';

SELECT NVL(MGRSSN,'No Manager')
FROM DEPARTMENT;

SELECT * FROM EMPLOYEE
WHERE ROWNUM <= 5;

SELECT FNAME || ' ' || LNAME
FROM EMPLOYEE;
